### ISSUE TITLE
Main navigation responsive

### ISSUE THREAD

**Issue by verpixelt** [hoodiehq/hood.ie#10]
The main (and sub)navigation has to be adjusted to response correctly to smaller view ports.

**Comment by zoepage** [comment]
do you want to add your design from #19?
and i'll add the functionality later?

**Comment by verpixelt** [comment]
Jep, perfect! Will do that. Should be finalised tomorrow evening.

**Comment by verpixelt** [comment]
I've added the main navigation changes with the last commits. You can see it's active state on /contribute.
I've styled it with the class `"its-active"` on `section class="nav"`. I still have to add a menu and close button but you could already start to develop the missing parts:
- [x] add and remove class on click
- [x] prevent page from scrolling when navigation layer is open
- [ ] finalise the animation on scroll

**Comment by verpixelt** [comment]
I've added the menu button. It has a toggled state with the class `.is-open`.
- [x] button class has to be added when menu is open

**Comment by zoepage** [comment]
awesome, will add this asap

**Comment by verpixelt** [comment]
Hey @zoepage what's up with this tasks?

**Comment by verpixelt** [comment]
?

**Comment by zoepage** [comment]
it's done.

**Comment by verpixelt** [comment]
Ola it isn't done. You can still scroll the page when the full screen nav is open + the behaviour (scroll back to top and nav fades in again) isn't implemented either.

**Comment by zoepage** [comment]
I talked with @ffffux about that before. You are right. I'll fix the "not scroll" fcn now. Sorry. 
That's why I reopened the issue...

(The other issue was implemented, like you might remember, but needs some fixing. It's post-launch now).

**Comment by zoepage** [comment]
non-scroll feature implemented with: b9033739d54290062e14df8ea22f4b7e946dd276

**Comment by verpixelt** [comment]
- [x] page behind the fullscreen nav still scrollable
- [ ] after resizes with open fullscreen nav (orientation change) bigger than the nav breakpoint close button doesn't close the nav anymore

**Comment by zoepage** [comment]
I'm still working on fixing the resize issue. I found the problem.
