### ISSUE TITLE
link underlines look weird in firefox 29 ubuntu

### ISSUE THREAD

**Issue by cebe** [hoodiehq/hood.ie#100]
Firefox 29.0 Ubuntu

![screenshot-2014-11-11t20 08 59](https://cloud.githubusercontent.com/assets/189796/4999051/acee7ffc-69de-11e4-813d-870fdd3634e0.png)

Looks like this line is responsible for drawing the underline which is placed a bit too high. https://github.com/hoodiehq/hood.ie/blob/gh-pages/dist/css/hoodie.css#L296

Here is a bit more zoom:

![screenshot-2014-11-11t20 11 29](https://cloud.githubusercontent.com/assets/189796/4999076/f44e43aa-69de-11e4-809c-33984f46cee1.png)

**Comment by lenareinhard** [comment]
yes, correct, that's the one. Thanks for the feedback! We'll look into it.

**Comment by chicgeek** [comment]
@cebe Firefox on Ubuntu is up to v33. Any reason you're using 29? Will investigate this further when I get off work.

**Comment by chicgeek** [comment]
This is the culprit. Checking to see if it's required by later versions of FF where it renders fine with the current styles.
https://github.com/hoodiehq/hood.ie/blob/gh-pages/dist/sass/_typo.scss#L188

```
@-moz-document url-prefix() {
    a {
        background-position: 0 rem-calc(18);
    }
}
```

**Comment by cebe** [comment]
There is no special reason, just a crappy old system that will break when trying to upgrade. If it is a Firefox bug in a version that is not widely used I am happy with closing this issue. However I am wondering why you aren't using simple text-decoration: underline in this case?

**Comment by lenareinhard** [comment]
@chicgeek wow, awesome! Thanks for taking the time to investigate!
@cebe good points, also regarding the underline question. We used the classic underline first, but it didn't work well with the font (looked too bold, and in some browsers looked even very similar to the screenshot above). In order to being able to set the underline precisely where it's supposed to, we decided to go for the solution we finally implemented.

**Comment by chicgeek** [comment]
Was hoping to make the fix and test it locally, but I'm not familiar with
Jekyll and unfortunately have not had time to figure it out.

Omitting this line definitely resolves the issue with FF29, but may nix a
fix put in for later FF versions, so it needs checking. Happy for someone
else to test/complete this, a few barriers in the way of me submitting
anything quite yet.

**Comment by janl** [comment]
@chicgeek  thanks so much for your help! <3

No bother if this doesn’t work for you, but if you want to try to set up jekyll:

```
> [sudo] gem install jekyll
> cd /path/to/hood.ie
> jekyll serve
```

Go to http://127.0.0.1:8000/ in your browser.
