### ISSUE TITLE
Page not working on Chromium & Firefox on Archlinux

### ISSUE THREAD

**Issue by lenareinhard** [hoodiehq/hood.ie#101]
Chromium: Version 38.0.2125.104 (290379) (64-bit)
Firefox: 33.0.1

![b2luet6cmaak-l0](https://cloud.githubusercontent.com/assets/3472712/4999187/5ad6ad32-69e0-11e4-8c6a-cbd63425b40c.png)

**Comment by badboy** [comment]
Same for me, works if I block fonts.googleapis.com (and thus the webfont).
I can load the required css and the linked fonts manually. Not sure why it blocks the rendering

**Comment by janl** [comment]
cc @espy 

Maybe this helps: https://support.mozilla.org/en-US/questions/958143

**Comment by janl** [comment]
Not all Linux: https://twitter.com/netzvagabund/status/532259825351421953

**Comment by lenareinhard** [comment]
see also #100 and #101

**Comment by janl** [comment]
Some more data points:
- https://twitter.com/blaue_flecken/status/532260576509329408
- https://twitter.com/Lady_Ada_King/status/532260860975415296
- https://twitter.com/MarkGavalda/status/532261171060293632 & https://twitter.com/MarkGavalda/status/532261853028958208

**Comment by janl** [comment]
FWIW, 8% Linux users on the site

**Comment by chesles** [comment]
If this helps, I see the font crossed out in chome's inspector. Network tab shows the fonts get downloaded, just not being rendered for some reason.

![2014-11-11-153221_621x391](https://cloud.githubusercontent.com/assets/149885/5000275/0dac75aa-69b8-11e4-8f36-317a0abd298f.png)

**Comment by candeira** [comment]
FWIW, it's working for me in stock Chrome/Ubuntu14.04. 

```
kandinski@desire:~$ head -n 1 /etc/apt/sources.list
deb mirror://mirror.aarnet.edu.au/pub/ubuntu/archive/ trusty main restricted universe multiverse
kandinski@desire:~$ google-chrome --version
Google Chrome 38.0.2125.111 
```

![image](https://cloud.githubusercontent.com/assets/91694/5000693/47ac8c88-6a42-11e4-87cb-143b5e452e1f.png)

**Comment by jo** [comment]
Same issue, also on Firefox 33.0.2 3.17.2-1-ARCH x86_64
Btw. similar problem here: http://blog.keithcirkel.co.uk/why-we-should-stop-using-grunt/

![screenshot from 2014-11-11 22 29 11](https://cloud.githubusercontent.com/assets/17586/5000997/c9df437c-69f1-11e4-9c22-f17fee80fa4f.png)

**Comment by chesles** [comment]
Similar problem with the google fonts site itself, actually. Other fonts there render, but not "Fira Sans".

**Comment by jo** [comment]
Seems like its a problem with that specific font, which is also used by the site I mentioned above.
![screenshot from 2014-11-11 22 49 47](https://cloud.githubusercontent.com/assets/17586/5001296/d5f64770-69f4-11e4-8cbe-429a230baa2a.png)

**Comment by espy** [comment]
Hello @chesles, @jo and @badboy , I've switched to self-hosting the font instead of pulling it from google, did that make any difference? Thanks!

**Comment by jo** [comment]
That has fixed it for me.

**Comment by badboy** [comment]
Much better now

**Comment by espy** [comment]
And there was much rejoicing!

![bildschirmfoto 2014-11-12 um 13 39 32](https://cloud.githubusercontent.com/assets/391124/5010294/674cf9b8-6a71-11e4-946f-cc30598656c4.png)

I'll consider this fixed now. Fingers crossed!

**Comment by verpixelt** [comment]
I'm sorry, but we have to do a little more work here. With the self hosted version we've increased the font loading time massively. With a simulated DSL connection it takes nearly 4sec(even worse on 3G or EDGE) until we get content displayed. This is far to long and in my opinion unacceptable. I will take a look into it.

**Comment by verpixelt** [comment]
I've developed a solution which might work out. I try to setup a virtual machine with Arch Linux tonight and test it.

**Comment by verpixelt** [comment]
We can finally close this issue with https://github.com/hoodiehq/hood.ie/pull/133. Additionally: we now score a 85/100(mobile) and 92/100(desktop)(speed) on the Google PageSpeed Insights, which is currently the best we can achieve.

**Comment by badboy** [comment]
Wooooah, that is fast.

![](http://media.giphy.com/media/lRnUWhmllPI9a/giphy.gif)

**Comment by zoepage** [comment]
WOOHOOOOOOO!!!!!! 
![](http://media3.giphy.com/media/5vBUXo7cbTEOc/giphy.gif)

**Comment by verpixelt** [comment]
😘😎thanks ;)
