### ISSUE TITLE
Redirect Blog [old domain] -> [new path]

### ISSUE THREAD

**Issue by ccoenen** [hoodiehq/hood.ie#103]
Hi there,

the blog used to be at blog.hood.ie, now it's at hood.ie/blog. This will break links that may be pointing to articles like the awesome TGIF-Series.

I'd like to request that you create a 301 Permanent Redirect. If you tell me what's your server, i'll gladly help. For Apache, the rule would look like this:

```
# inside a blog.hood.ie virtual host
RewriteEngine on
RewriteRule ^/(.*)$ http://hood.ie/blog/$1 [L,R=301]
```

L -> last rule
R=301 -> redirect as 301 (permanent)

**Comment by janl** [comment]
> On 11 Nov 2014, at 20:40 , Claudius Coenen notifications@github.com wrote:
> 
> Hi there,
> 
> the blog used to be at blog.hood.ie, now it's at hood.ie/blog. This will break links that may be pointing to articles like the awesome TGIF-Series.
> 
> I'd like to request that you create a 301 Permanent Redirect. If you tell me what's your server, i'll gladly help. For Apache, the rule would look like this:
> 
> # inside a blog.hood.ie virtual host
> 
> RewriteEngine on
> RewriteRule ^/(.*)$ http://hood.ie/blog/$1 [L,R=301]
> 
> L -> last rule
> R=301 -> redirect as 301 (permanent)

We have setup a redirect. Which links are now working for you? The old articles were all migrated to the new blog.

Best

## Jan

**Comment by ccoenen** [comment]
You're right. I'm sorry. I assumed, since the feed itself failed, there must be no redirect in place at all. If i find a URL that's not working as expected, i'll reopen.

Sorry for the confusion!

**Comment by janl** [comment]
Absolutely no worries :)
