### ISSUE TITLE
Please bring back RSS-Feeds

### ISSUE THREAD

**Issue by ccoenen** [hoodiehq/hood.ie#105]
The "old" Blog had a RSS Feed. I'd love to have one for the new one, too!

For "onboarding" of the old folks (like me) you should also forward the old RSS URL to the new one. Some Readers will follow a redirect. Another good practice would be to have an 'End-of-Life' entry at the old URL, which mentions the new feed address. (this can also be incorporated in the aforementioned virtual host in #103 )

**Comment by janl** [comment]
Sorry, I dropped this one. We will definitely have an RSS feed and redirects and everything.

**Comment by ccoenen** [comment]
Cheers!

**Comment by lenareinhard** [comment]
working on implementing https://github.com/snaptortoise/jekyll-rss-feeds

**Comment by verpixelt** [comment]
If you need help, ping me.

**Comment by lenareinhard** [comment]
@verpixelt can you take this over? I won't be able to do it before thursday, if that's enough, I can work on it then

**Comment by verpixelt** [comment]
I guess I get it fixed before thursday.

**Comment by verpixelt** [comment]
At this point it works half the way. You can add the Hoodie blog to your RSS reader by using http://hood.ie/feed.xml. Reeder doesn't display any title or description for me. I'll try to figure out why tomorrow.

**Comment by ccoenen** [comment]
If the url stays like that, the head.html needs a slight alteration right here:
https://github.com/hoodiehq/hood.ie/blob/8a8d7e73542331b5fc9d6ae6d87ca15740c327b9/_includes/head.html#L42 (still says `/blog/feed.xml`)

And found another one, on one of the TGIF posts:
https://github.com/hoodiehq/hood.ie/blame/86401d571d10c3c258a9087c26c08b436a02b1b4/_posts/2014-01-10-tgif-17-focus-structure-alpacas-killing-freedom-in-the-name-of-safety.md#L109

**Comment by verpixelt** [comment]
Thanks Claudius for the hint. I'll take a look at it =)

**Comment by lenareinhard** [comment]
what's the status here?

**Comment by verpixelt** [comment]
After I've changed the xml url to hood.ie/feed.xml my RSS reader (Reeder with feedly) is able to find the feed but doesn't display a title, description or any posts at all. Any idea?

**Comment by badboy** [comment]
http://hood.ie/feed.xml returns HTML first (the default layout).
The problem:

```
---
layout: default-blue
---
```

Change that layout to `null` to disable it and it won't use any and therefore only return the feed content.

**Comment by verpixelt** [comment]
Thanks @badboy I'll change that later :)

**Comment by badboy** [comment]
and then I can finally add it to my feed reader again and never miss a TGIF anymore! \o/

**Comment by verpixelt** [comment]
![rss-fixed](https://cloud.githubusercontent.com/assets/1640079/5777677/14eed2c0-9d95-11e4-9267-1a0672db5725.png)
Aaaaand fixed! Thanks @badboy for the hint ;)

**Comment by lenareinhard** [comment]
Yeah, yeah, yeah! 
http://media.giphy.com/media/XWKrUYz1N5J7i/giphy.gif

**Comment by lenareinhard** [comment]
Feed still not working here (not recognized by RSS readers, haven't received any of the latest blog posts in there, and can't even add it to any readers), plus W3C Feed Validator gives me no validation either.

Can anybody reproduce this issue? Or, rather: can anybody aside from @verpixelt confirm that the feed is working now?

**Comment by NickColley** [comment]
I think you need an empty yaml block, seem to remember null breaking something.

https://github.com/snaptortoise/jekyll-rss-feeds#miscellany

Edit: Maybe not, thought i'd mention it tho'.

**Comment by verpixelt** [comment]
Does it work for you if you use http://hood.ie/feed.xml ? Http://hood.ie doesn't do a thing for me either.

**Comment by badboy** [comment]
http://hood.ie/feed.xml works fine in my RSS reader. Also it spits out correct XML.
There are a few problems though with regard to the feed format: http://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fhood.ie%2Ffeed.xml

I guess the protocol is necessary here (`http://`), might be necessary on the alternate link on hood.ie as well

**Comment by lenareinhard** [comment]
@verpixelt no, none of these work, none of these are validated.

**Comment by verpixelt** [comment]
Can you try it once more, please. I guess I've fixed it ;) Should work with hood.ie by now.

**Comment by lenareinhard** [comment]
now it works :) thanks!

**Comment by verpixelt** [comment]
\o/!!
