### ISSUE TITLE
Main Navigation: ABOUT link is always active

### ISSUE THREAD

**Issue by lenareinhard** [hoodiehq/hood.ie#106]
… on any page I visit. Goes for all browsers, navigation setting is wrong.

**Comment by svnlto** [comment]
i think this has been introducted by this commit https://github.com/hoodiehq/hood.ie/commit/ba94d54604fb66bc884153ccbee23dc817a40b32

**Comment by lenareinhard** [comment]
fixed, so sorry https://github.com/hoodiehq/hood.ie/commit/045b874d02bdb38beacce7371ee0256a531211d8
