### ISSUE TITLE
Page looks broken in Windows 7 (might be web font issue as well)

### ISSUE THREAD

**Issue by lenareinhard** [hoodiehq/hood.ie#108]
Windows 7, Chrome 38

![b2pasktciae-rvp](https://cloud.githubusercontent.com/assets/3472712/5008727/d7621d08-6a5f-11e4-9af1-43f2d0afe1ec.png)

**Comment by verpixelt** [comment]
Is this issue still relevant? I'm unfortunately unable to test it right now.
