### ISSUE TITLE
newsletter signup has no submit

### ISSUE THREAD

**Issue by zoepage** [hoodiehq/hood.ie#109]
The newsletter input has no functionality behind it. Seems like, we forgot it during the progress. Need to fix it asap...

**Comment by lenareinhard** [comment]
The functionality is here in line 48-54: https://github.com/hoodiehq/hood.ie-website-old/blob/master/src/index.html

**Comment by zoepage** [comment]
Removing the button and fetching the submit event by keypress: enter.
