### ISSUE TITLE
Styling table

### ISSUE THREAD

**Issue by verpixelt** [hoodiehq/hood.ie#11]
The sponsoring table on /sponsoring has to be styled(also responsive).
![sponsoring-table](https://cloud.githubusercontent.com/assets/1640079/4783117/da11d132-5d18-11e4-94ab-c205779cd47d.png)

**Comment by zoepage** [comment]
i can do that. is it already responsive?

**Comment by verpixelt** [comment]
Nope it isn't. Would be great if you can do that, too. Making the table content x-scrollable should be enough I guess.

**Comment by zoepage** [comment]
check. will do!

**Comment by zoepage** [comment]
resp: done down to 400px. 
styling done...
