### ISSUE TITLE
Invisible Header too large. Blocks texts and links.

### ISSUE THREAD

**Issue by ghost** [hoodiehq/hood.ie#110]
![screen shot 2014-11-12 at 18 15 48](https://cloud.githubusercontent.com/assets/131438/5014701/2eff7302-6a98-11e4-94bc-77603ce890eb.png)

Effect: I couldn't click the links embedded in the text, when they've been displayed in the upper area of the browser.

Assumption: the header slides out and gets html-class invisible. The class uses css attributes visibility, opaticy and more. Browsers interner visibility: hidden; and opacity: 0; as "transparent" and catch the click events on the header not on the anchors.

**Comment by zoepage** [comment]
Header height is on 206px. Should be 104.  I'll check it asap! Thank you very much! <3

**Comment by espy** [comment]
Sorry, this was a last-minute hotfix while I was already setting up upfront. The 206px is for the animated header. Have you worked on this yet, @zoepage ? Otherwise I can do it now.
