### ISSUE TITLE
Interaction states

### ISSUE THREAD

**Issue by NickColley** [hoodiehq/hood.ie#113]
What do you think to having more interaction states throughout the site so it's obvious when you're hovering over elements, focused on them etc.

I'd love to help out but thought I'd see what you think before trying anything. :)

**Comment by janl** [comment]
just for your consideration, not anything for or against this suggestion: there is no “hover” on mobile

**Comment by NickColley** [comment]
Yeah was just an example -- most of the benefit would be from the active/focus states.

**Comment by zoepage** [comment]
Thank you @nickcolley for your suggestions. If you have something special in mind, let's discuss that! :)

**Comment by zoepage** [comment]
Closing this after deprecation.
