### ISSUE TITLE
Placeholder content still visible on IRC page

### ISSUE THREAD

**Issue by chrisdwheatley** [hoodiehq/hood.ie#116]
Looks like there is still some placeholder pieces of content in the left hand side on the IRC page, see http://hood.ie/irc & https://github.com/hoodiehq/hood.ie/blob/b1de03fd394cb7b469b2685f9863759584525792/irc/index.html#L19

If someone lets me know what to put there or whether to just remove those pieces of text I'm happy to submit a PR.

**Comment by zoepage** [comment]
Oh, we musst have missed that!
Thank you for pointing this out! :)

The text can be removed as long as the aside tag stays ;)

Thank you for your help!
<3

**Comment by zoepage** [comment]
Done!

**Comment by chrisdwheatley** [comment]
Yay! :smile:
