### ISSUE TITLE
Doc request - concise technical explanation

### ISSUE THREAD

**Issue by nichoth** [hoodiehq/hood.ie#127]
I've looked through the website, and I would really enjoy a simple lower level explanation of what hoodie _is_ (the tech stack). Does it use PouchDB? What does hoodie give me that I couldn't get using Pouch & Couch by themselves? What design patterns does it use?

**Comment by zoepage** [comment]
Thanks for the suggestion! I'll take care of that :)

**Comment by zoepage** [comment]
hey @nichoth!
today i added the concepts: http://docs.hood.ie/en/hoodieverse/hoodie-concepts.html
will add more content soon.

enjoy!
