### ISSUE TITLE
Missing Ligatures in Safari

### ISSUE THREAD

**Issue by verpixelt** [hoodiehq/hood.ie#134]
Currently we're to "hotfix"-ing the ligature issue b/c of troubles with the base64 font files. This is done by a font-feature-setting which apparently isn't supported in Safari. I'm working on the font files, so we hopefully can close this pretty soon.

**Comment by verpixelt** [comment]
Solved with 5671331e25b40db7207c352e0f1657d071baaad2 🎉🎊

**Comment by janl** [comment]
Boom! Thank you, this is amazing, the site is _FAST_ :D

**Comment by verpixelt** [comment]
It's my pleasure! Next step: Woff2 support, which would get us another -30% file size, for modern browsers ;)
