### ISSUE TITLE
Responsive behaviour /events

### ISSUE THREAD

**Issue by verpixelt** [hoodiehq/hood.ie#15]
The /events page has to be adjusted to behave correctly on smaller view ports.

**Comment by espy** [comment]
Fixed in 0237beaa

**Comment by verpixelt** [comment]
The event page is horizontally scrollable.
![x-scrollable](https://cloud.githubusercontent.com/assets/1640079/4783370/d86234de-5d23-11e4-9b1c-c37b6729c76e.png)

**Comment by espy** [comment]
Haha, good catch :D 

The reason was fun:

![bildschirmfoto 2014-10-26 um 16 23 45](https://cloud.githubusercontent.com/assets/391124/4783381/545fa2ec-5d24-11e4-8bf4-07083ccb4282.png)

Fixed it both in the source spreadsheet and in 5917c49fc4.
