### ISSUE TITLE
Chat iframe on Firefox/Mac is off

### ISSUE THREAD

**Issue by janl** [hoodiehq/hood.ie#167]
![screen shot 2015-07-01 at 21 29 05](https://cloud.githubusercontent.com/assets/11321/8463091/689c3c98-2038-11e5-82d1-5de139450f0a.png)

We don’t show the logos in any of the other browsers.

cc @espy @zoepage @verpixelt

**Comment by varjmes** [comment]
This is also an issue in Safari and Chrome. It didn't used to be a problem.

**Comment by janl** [comment]
Found while testing https://github.com/hoodiehq/hood.ie/pull/166 to stop the scrolling.

**Comment by janl** [comment]
@Charlotteis are you saying you see half a logo each in Safari and Chrome?

**Comment by varjmes** [comment]
@janl now that I am more aware of the actual issue, I retract my previous comment :)

**Comment by verpixelt** [comment]
Which page are we talking about?

**Comment by varjmes** [comment]
@verpixelt hood.ie/chat

**Comment by espy** [comment]
I think I've got it, gimme a minute.

**Comment by verpixelt** [comment]
The logos are there in all browsers if you scroll inside the iFrame. We have to set a proper height and disable scrolling.

**Comment by espy** [comment]
Wait, Stefan changed the color of the button, so we have control over the content of the iframe, right? let's just fix that instead of fiddling around with scroll positions etc.

**Comment by espy** [comment]
Ok, apparently @boennemann and @christophwitzko are going to re-implement the iframe as a form :)

**Comment by janl** [comment]
We have the stop scrolling fix here: https://github.com/hoodiehq/hood.ie/pull/166

The problem is now that FF clips it differently than Safari or Chrome.

**Comment by boennemann** [comment]
#178
