### ISSUE TITLE
add friends page

### ISSUE THREAD

**Issue by zoepage** [hoodiehq/hood.ie#171]
- hapi
- couchdb
- nodejs
- travis
  ...

**Comment by zoepage** [comment]
http://hood.ie/friends/
Who is still missing?

cc @gr2m @espy ?

**Comment by gr2m** [comment]
I think the idea was to make URLs like http://hood.ie/and/friends (for the landing page) and then http://hood.ie/and/hapi, http://hood.ie/and/couchdb, http://hood.ie/and/pouchdb, http://hood.ie/and/yet, ... 

I think we we start with CouchDB / Hapi / PouchDB that'd be good enough for a start. And then it would be great to add pages for companies we're friends with, and MVC frameworks like Backbone, Angular, Ember, then we could make one for Meteor as people keep asking how these two compare etc etc

**Comment by zoepage** [comment]
Ah okay :)

Still not sure about the content. 

What would be written on e.g.  and/couchdb ?

**Comment by gr2m** [comment]
I think this is probably out of scope for 1.0, so feel free to close it for now.

I think the content pages would look different for CouchDB (a technology that Hoodie uses), &yet (A company and friends that supports us) and Ember (An MVC framework that hoodie place nicely with). 

at `/and/couchdb` the content would explain why Hoodie is using it and how.
