### ISSUE TITLE
Navigaion on smaller screens

### ISSUE THREAD

**Issue by verpixelt** [hoodiehq/hood.ie#19]
This is my proposal for the navigation(full screen layer) on smaller screens(< 55em/880px) after you've hit the hamburger icon.
![nav-mobile](https://cloud.githubusercontent.com/assets/1640079/4783602/8e96fb1e-5d2d-11e4-9b7c-44071aa3115d.png)

**Comment by verpixelt** [comment]
I've published a branch with this draft (no functionality included). Do not merge!

**Comment by zoepage** [comment]
i think it looks amazing! <3

**Comment by verpixelt** [comment]
I've added a breakpoint which hides the navigation below 64em (1024px). Navigation is visible again, when the menu active class is set.
