### ISSUE TITLE
Navigation breaks after "tabing" through it

### ISSUE THREAD

**Issue by verpixelt** [hoodiehq/hood.ie#191]
In Chrome 44.0.2403.155 on OS X 10.10.4 the right part of the navigation breaks after using tab to navigate it.
<img width="1820" alt="tab-broken" src="https://cloud.githubusercontent.com/assets/1640079/9219871/59dd1dfa-40de-11e5-8999-f291f4e8062a.png">

**Comment by NickColley** [comment]
Google Chrome Version 40.0.2214.111 (64-bit), Linux Fedora 20 :sheep: 

![tabexample](https://cloud.githubusercontent.com/assets/2445413/9233709/7fdec5c8-412c-11e5-9a06-889cdf84b9d5.gif)
