### ISSUE TITLE
Fix Cheatsheet broken link on get started page

### ISSUE THREAD

**Issue by busyxin** [hoodiehq/hood.ie#192]
The step 6 from the get started page is displaying two broken links to the cheat sheets

**Comment by varjmes** [comment]
Hi @busyxin! This will likely be an issue with https://github.com/hoodiehq/hoodie-css where the presentations haven't been added to the repository yet! Looks like one that @zoepage can help with :)

**Comment by zoepage** [comment]
@busyxin the cheat sheets can be found here: https://github.com/hoodiehq/hood.ie/tree/gh-pages/dist1/presentations

We still need to decide if we'll have a dist folder with website content and if, how it's called.
Any thoughts on that @espy @Charlotteis @Althaire?

**Comment by varjmes** [comment]
It's good to have a central store, though I don't know if hoodie-css or even the main hood.ie repo is the right place for it. What about creating a new repo to store these things and link to them from wherever. Means people can easily add their presentations without having to do the whole setup process of the main hood.ie repo. @zoepage

**Comment by zoepage** [comment]
I don't think adding another repository will be a good idea. 

We thought about to options before. 
1. Content which could / should be accessed from more than one repository -> hoodie-CSS
1. Content accessed from just one repository -> in specific repository.

**Comment by varjmes** [comment]
Okay then, I'm happy enough :dancer: 

So to close this issue we need to replace the links with the `dist1` links?

**Comment by zoepage** [comment]
We first need to decide on the folder structure. This is Kevins job now.

**Comment by varjmes** [comment]
ok, thanks for clarification :)

**Comment by varjmes** [comment]
There are broken links all over the site because of this folder renaming, check the references on this issue for other examples :)

**Comment by gilmoreorless** [comment]
I found my way to this issue after looking at the [Contributing to Hoodie](http://hood.ie/blog/contributing-to-hoodie.html) blog post. The images there are broken because they were in the `dist` directory.
I realised that it wouldn't be a quick fix to make the images work again, as the `dist` renaming seemed to be part of a much bigger piece of work. However, as it stands there are a lot of broken images in blog posts on the site right now.

I'll slowly back away from changing anything, as it looks like you're already on to the situation. But as it stands right now, all these files have broken references while the `dist` directory is missing:

```
$ grep -rl --exclude-dir=_site --exclude-dir=node_modules '/dist/' *
_posts/2013-06-08-hacker-news-thread-about-hoodie.md
_posts/2013-07-08-big-things-to-come-building-the-hoodie-plugin-architecture-making-hoodie-plugin-ready.md
_posts/2013-07-17-hoodieberry-pi-hoodie-on-raspberry-pi-3.md
_posts/2013-08-20-meet-the-css-community-at-cssconf-eu.md
_posts/2013-08-21-announcement-open-source-funding-by-nlnet-for-hoodie-granted.md
_posts/2013-08-22-hoodies-in-rl-frontendconf-ch-august-29-30-zurich.md
_posts/2013-08-27-hoodies-irl-jsconf-eu.md
_posts/2013-09-10-going-south-announcing-africa-hack-trip.md
_posts/2013-09-15-i-have-a-dreamcode-build-apps-not-backends-jsconf-eu-2013-recap-part-1.md
_posts/2013-09-27-tgif-nerdboat-interviewing-developers-diversity-gta-v-and-a-skype-killer.md
_posts/2013-10-04-tgif-big-data-joblint-improving-os-contribution-lavabit-lxjs.md
_posts/2013-10-11-tgif-9-reponsibility-is-not-a-choice-its-a-job.md
_posts/2013-10-25-team-hoodie-is-visiting-mozilla-festival.md
_posts/2013-11-03-plugins.md
_posts/2013-11-08-tgif-11-be-offline-and-transparent-draw-animals-reconsider-semantics-wear-beards-dont-be-a-superhero-and-build-a-better-web.md
_posts/2013-11-21-tgif-13-open-doors-put-everyone-on-support-unbrand-your-life-block-surveillance-have-a-pizza-and-get-kurt-cobains-college-haircut.md
_posts/2013-11-27-offline-first-and-the-circle-of-web.md
_posts/2013-11-29-tgif-14-watering-facepalms-enjoying-science-loving-sheep-letting-work-wait-und-ab-jetzt-auch-auf-deutsch.md
_posts/2013-12-17-offline-first-and-the-circle-of-web-part-ii-breaking-the-circle.md
_posts/2013-12-20-oh-what-a-year-hoodie-says-thank-you.md
_posts/2014-01-08-the-hoodie-why-1-we-have-a-dreamcode.md
_posts/2014-01-10-tgif-17-focus-structure-alpacas-killing-freedom-in-the-name-of-safety.md
_posts/2014-01-23-even-better-github-organisations-with-ubersicht.md
_posts/2014-01-24-tgif-19-rants-at-our-future-selves-the-web-open-products-and-strangers.md
_posts/2014-02-07-tgif-21-yep-passionate-sloths-and-moderate-water-coolers-taking-lessons-in-physics.md
_posts/2014-02-14-tgif-22-relaxed-bingo-loving-compiled-schnitzel-secretly-running-the-world.md
_posts/2014-02-19-offline-first-meetup-1-in-berlin.md
_posts/2014-02-24-meet-the-hoodies-episode-2-ola.md
_posts/2014-02-28-happy-birthday-hoodie.md
_posts/2014-03-07-tgif-24.md
_posts/2014-03-17-hoodie-ios-say-hi-to-hoohoodie.md
_posts/2014-03-21-friday-friday-so-good-to-me-and-tgif-26.md
_posts/2014-04-04-every-friday-is-a-good-friday-tgif-28.md
_posts/2014-04-08-hoodietime-events-and-conferences-with-hoodies-in-april-and-may.md
_posts/2014-04-16-introducing-the-hoodie-community-code-of-conduct.md
_posts/2014-04-18-friday-friday-it-was-all-i-hoped-it-would-be-tgif-30.md
_posts/2014-05-09-taking-back-friday-tgif-33.md
_posts/2014-05-27-a-hoodie-for-you-8-katrin-apel.md
_posts/2014-09-09-semantic-releases.md
_posts/2015-04-27-jsunconf-recap.md
_posts/2015-05-21-contributing-to-hoodie.md
contribute/index.html
get-help/index.html
gruntfile.js
```

**Comment by verpixelt** [comment]
All content relevant links are now pointing to the dist1 folder inside the hoodie-css repo.

**Comment by varjmes** [comment]
Thank you all! :)
