### ISSUE TITLE
Automatically test for insensitive wording using alex

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hood.ie#194]
see http://alexjs.com/

**Comment by tsriram** [comment]
Are you still looking at getting this done? I can try helping :)

**Comment by varjmes** [comment]
@tsriram absolutely!

**Comment by tsriram** [comment]
Cool. Should I be adding this as a grunt task and make it run in `default`,  `watch` & `build`? Or would you prefer an npm script?

**Comment by gr2m** [comment]
@tsriram I think an npm script would be better. We will start soon on re-doing our website (#312), and npm script will be simpler to migrate :) Thanks a lot for looking into it 👍

**Comment by tsriram** [comment]
@gr2m great. One more clarification - the npm script should run all markdown files in _posts through alex.js and report, right?

**Comment by varjmes** [comment]
@gr2m what do you think? I think it should be run on all files in the site, not just .md's?

**Comment by tsriram** [comment]
@gr2m @Charlotteis have created a WIP PR #333. Please take a look and comment.
