### ISSUE TITLE
On Linux, when couchdb is not installed, starting hood.ie fails non-obviously because it starts launch-couchdb-from-app.sh which assumes OSX

### ISSUE THREAD

**Issue by thomasvs** [hoodiehq/hood.ie#196]
It took me a while to realize that I simply hadn't installed couchdb yet on this new computer.  A lot of headscratching that could have been solved by the script simply erroring out on non-macosx if couchdb is not available.

**Comment by gr2m** [comment]
@thomasvs sorry for all the trouble :/ We are working on a new hoodie-server which already dropped the CouchDB dependency altogether, it's starting a PouchDB Server instance by default. It's not ready for prime time yet, but that's what we are focusing on right now.

But we can keep this open for others who run into the same problem for the time being

**Comment by janl** [comment]
I’ve raised an issue with node-multicouch that explains how to fix the underlying. Let’s keep this open until Hoodie behaves correctly.

**Comment by gr2m** [comment]
Has this been resolved? If not can we move it to https://github.com/hoodiehq/node-multicouch to keep issues here related to the website only?

**Comment by janl** [comment]
This has been fixed in https://github.com/hoodiehq/node-multicouch/commit/3c0588db6bee25c94b34b82585aa896626698901

**Comment by gr2m** [comment]
awesome, thanks :+1:
