### ISSUE TITLE
RSS feeds for jekyll blogs

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hood.ie#199]
Seems to be easier now. See https://github.com/blog/2053-easier-feeds-for-github-pages

**Comment by gr2m** [comment]
looks like http://hood.ie/feed.xml works now :+1: thanks @antoinelyset for checking

**Comment by antoinelyset** [comment]
For the record,

This is what the current feed looks like (whole articles with images too) : 

![rss-hoodie-custom](https://cloud.githubusercontent.com/assets/1465371/12532084/3ff025b4-c20b-11e5-967c-1eddc221865b.png)

This is what it _could_ look like (titles and excerpts) : 

![rss-jekyll-feed](https://cloud.githubusercontent.com/assets/1465371/12532085/3ff078ac-c20b-11e5-8856-253faf0e1d13.png)
I don't use RSS so I can't pick the right one.
We are staying with the current one but if needed, it's **really** simple to change.
