### ISSUE TITLE
Broken images on why we have a dreamcode

### ISSUE THREAD

**Issue by courajs** [hoodiehq/hood.ie#202]
http://hood.ie/blog/the-hoodie-why-1-we-have-a-dreamcode.html has several broken images

**Comment by varjmes** [comment]
Hi @AaronSikes, I don't seem to see any broken images here. As far as I can see there are two images and they are both showing up? Of course, I may be missing something, happy to help if I have :)

**Comment by varjmes** [comment]
Please ignore that comment! This is indeed an issue, closing this one in favour of this issue here: #192. Thank you for letting us know!
