### ISSUE TITLE
Serving Fira Sans

### ISSUE THREAD

**Issue by verpixelt** [hoodiehq/hood.ie#21]
What's the actual idea for serving Fira Sans?
I've read the following article: http://bdadam.com/blog/loading-webfonts-with-high-performance.html which explains a solution of how to serve the font base64 encoded (inline in the head). The approach sounds pretty interesting.

**Comment by zoepage** [comment]
see #101

**Comment by verpixelt** [comment]
Let's close this issue and keep on with it in #101.
