### ISSUE TITLE
Link underlines in headlines are off

### ISSUE THREAD

**Issue by janl** [hoodiehq/hood.ie#217]
Latest Safari on Mac:

![screen shot 2015-12-10 at 20 05 45](https://cloud.githubusercontent.com/assets/11321/11725313/6a14618e-9f79-11e5-9e88-07ba63e6c7f3.png)

On: http://hood.ie/blog/we-have-been-busy.html

**Comment by varjmes** [comment]
Already an issue open here: https://github.com/hoodiehq/hoodie-css/issues/42
