### ISSUE TITLE
Hood.ie friends SVG logos

### ISSUE THREAD

**Issue by verpixelt** [hoodiehq/hood.ie#22]
Mail the hood.ie friends to request their logos as SVG.

**Comment by NickColley** [comment]
PouchDB: [raw](https://raw.githubusercontent.com/pouchdb/pouchdb/master/docs/static/img/mark.svg)   - [img](http://pouchdb.com/static/img/mark.svg)

**Comment by lenareinhard** [comment]
thanks, @nickcolley <3
- [x] PouchDB
- [x] CouchDB: https://svn.apache.org/repos/asf/couchdb/supplement/logo/couchdb-logo.svg
- [x] Node.js http://de.wikipedia.org/wiki/Datei:Node.js_Logo.svg
- [x] &yet -> contacted, found https://apps.andyet.com/images/logo.svg
- [x] nlnet https://nlnet.nl/logo/banner.svg
- [x] Travis -> I got it, please let me know when you want to implement it
- [x] Third Wave -> contacted, received logo

**Comment by verpixelt** [comment]
I've included the first ones. If you could send me the Travis logo file, that would be perfect.

**Comment by verpixelt** [comment]
- [x] add Travis with commit 79c667bbbcec83df93362171647a649a13f82af5
  left:
- [x] &yet
- [x] Third Wave

**Comment by lenareinhard** [comment]
sent ThirdWave to @verpixelt, and found &yet: https://apps.andyet.com/images/logo.svg
