### ISSUE TITLE
does not work on windows ?

### ISSUE THREAD

**Issue by ramstein74** [hoodiehq/hood.ie#222]
![image](https://cloud.githubusercontent.com/assets/1210858/12332985/7598f278-bae9-11e5-9158-e55ba75a15cc.png)

**Comment by gr2m** [comment]
I can’t help debugging, but it definitely works for other Windows users.

We are working on a new version, can you try if you can start that? 
https://github.com/hoodiehq/hoodie-app-something-tracker

**Comment by ramstein74** [comment]
it works but if i reload the page is empty of records.
I expected pouchdb to be used.
I need an offline first app.

thank you
António

2016-01-14 23:55 GMT+00:00 Gregor Martynus notifications@github.com:

**Comment by gr2m** [comment]
We resolved that issue meanwhile, and created a follow up issue for a related problem here: https://github.com/hoodiehq/hoodie-app-tracker/issues/19
