### ISSUE TITLE
[Accessibility] Give the Hoodie Logo meaningful alternative text

### ISSUE THREAD

**Issue by varjmes** [hoodiehq/hood.ie#223]
# The Bug :bug:

When navigating through the Hoodie website with assistive technology (AT), the logo image has no contextual information, meaning that nothing will be read out that is useful in letting us know what the image does (it links to the home page).

Using OSX Voiceover and tabbing to the image, you will hear `link slash banner 1 item`. Now, I'm sure
that seasoned users of AT will know that `slash` means linking to the homepage, but it's better
to be obvious about these things!
# Steps to fix :wrench:
- [ ] Claim this issue (comment below, or assign yourself if you are part of the Hoodie Org)
- [ ] Fork and clone the repository
- [ ] Add alt text to the logo, something like `Logo link to Homepage`
  - [ ] In the main [`header.html`](https://github.com/hoodiehq/hood.ie/blob/gh-pages/_includes/header.html#L3)
  - [ ] In the [`header-intro.html`](https://github.com/hoodiehq/hood.ie/blob/gh-pages/_includes/header-intro.html#L4)
  - [ ] In the [`header-initiatives.html`](https://github.com/hoodiehq/hood.ie/blob/gh-pages/_includes/header-initiatives.html#L4)
  - [ ] In the [`header-get-help.html`](https://github.com/hoodiehq/hood.ie/blob/gh-pages/_includes/header-initiatives.html#L4)
  - [ ] In the [`header-contribute.html`](https://github.com/hoodiehq/hood.ie/blob/gh-pages/_includes/header-contribute.html#L4)
  - [ ] In the [`header-contact.html`](https://github.com/hoodiehq/hood.ie/blob/gh-pages/_includes/header-contact.html#L4)
  - [ ] In the [`header-community.html`](https://github.com/hoodiehq/hood.ie/blob/gh-pages/_includes/header-community.html#L4)
  - [ ] In the [`header-blog.html`](https://github.com/hoodiehq/hood.ie/blob/gh-pages/_includes/header-blog.html#L4)
  - [ ] In the [`header-animals.html`](https://github.com/hoodiehq/hood.ie/blob/gh-pages/_includes/header-animals.html#L4)
  - [ ] In the [`header-about.html`](https://github.com/hoodiehq/hood.ie/blob/gh-pages/_includes/header-about.html#L4)
- [ ] Commit your changes as one commit entitled `fix(a11y): add alt text to header logo`
- [ ] Submit a Pull Request
- [ ] Have your PR reviewed & merged

Ping me in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/charlotteis) if you have any questions :sparkles:

**Comment by stevedotmt** [comment]
I will take this later this week. Can we use the alt tag of "Hoodie Logo linking to Homepage"?

**Comment by KittyGiraudel** [comment]
Should be fixed with https://github.com/hoodiehq/hood.ie/pull/224. :)

**Comment by chrisdemars** [comment]
I too wanted to work on this. Any other a11y issues surfacing?

**Comment by chrisdemars** [comment]
Nevermind, @SteveAzz has first dibs.

**Comment by varjmes** [comment]
@SteveAzz sorry Steve, it looks like someone else got there before you.
@HugoGiraudel to encourage folks new to programming / making PRs we tend to let the first person who responds to the issue, take the issue. But as you've already done the work, I'm happy to accept this. Just a note for the future. And thank you for the work!

@SteveAzz, @chrisdemars I will be writing future accessibility issues and will let you both know when I've gotten around to doing them. Feel free to see if you can discover issues in the website and want to have a go at fixing them!

**Comment by KittyGiraudel** [comment]
@Charlotteis Sorry.

**Comment by chrisdemars** [comment]
Sounds like a plan.

**Comment by stevedotmt** [comment]
Awesome thanks, Good job @HugoGiraudel

**Comment by varjmes** [comment]
> @Charlotteis Sorry.

No need for apologies! Thank you for your work :sparkles:

**Comment by varjmes** [comment]
^ @HugoGiraudel
