### ISSUE TITLE
Headings broken in blog

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hood.ie#229]
seen in 
- http://hood.ie/blog/meet-the-hoodies-jenn-turner.html
- http://hood.ie/blog/Charlotte-Spencer-meet-the-hoodies-2.html
- http://hood.ie/blog/Alex-Feyerke-meet-the-hoodies-1.html

Odd, I’m quite sure this worked before?

**Comment by NickColley** [comment]
Not sure but I think stricter markdown parsers require a space between the # and text.

Those look like `###*What’s your favourite animal?*`

Maybe the jekyll version changed when deploying?

**Comment by gr2m** [comment]
yes, tested it locally, that fixed it. I’ve also sean heading, this fixes it

``` diff
-###*What’s your favourite animal?*
+### What’s your favourite animal?
```

There are also headings ending with `*###` – no idea where this came from.

@nickcolley can you fix the post and maybe check if there are others? I’m heads down on other things rn

**Comment by NickColley** [comment]
Sure I'll look at this asap.

**Comment by NickColley** [comment]
https://github.com/hoodiehq/hood.ie/pull/233
