### ISSUE TITLE
Update Footer links and language

### ISSUE THREAD

**Issue by jennwrites** [hoodiehq/hood.ie#231]
### :octocat: Starter Issue

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :)

---
### :bug: The Bug

Not technically a bug :relaxed: more of an update! We need to update the footer across the whole site: http://hood.ie/
- [x] Claim this issue (@kazekagegaara)
- [ ] Go to the ['footer.html' file](https://github.com/hoodiehq/hood.ie/blob/gh-pages/_includes/footer.html)
- [ ] Where the code is displayed (below a grey field) click on the pencil icon to the very right of the screen. 
  <img width="229" alt="screen shot 2016-02-23 at 17 50 39" src="https://cloud.githubusercontent.com/assets/2582805/13269553/641360f6-da56-11e5-8a5e-79dacd9ef39c.png">
- [ ] Make your changes in the text field.
- [ ] Describe your edits briefly.
- [ ] Select the option to create a patch or a branch to begin the Pull Request process. 
- [ ] Start a Pull Request.  
  (If this is your first, welcome :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request)
- [ ] Change "Hood.ie" to "Hoodie || hood.ie" and keep hyperlink the same
- [ ] Remove Plugins link
- [ ] Update the year in the licensing information to 2016.
- [ ] You are done :clap: comment below that your pull request is ready for review 

:tada: Once all three are completed this issue can be considered closed. :relaxed: 

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by kazekagegaara** [comment]
I'd like to take this, if there's no one else.

**Comment by NickColley** [comment]
@kazekagegaara that'd be awesome thanks, I've updated the post to say you're working on this! :)

**Comment by kazekagegaara** [comment]
Please review.

**Comment by jennwrites** [comment]
Just catching up, looks great @kazekagegaara! Thank you :tada:

**Comment by kazekagegaara** [comment]
Thank you letting me contribute!
