### ISSUE TITLE
Strange link on site.

### ISSUE THREAD

**Issue by crswll** [hoodiehq/hood.ie#237]
I was clicking around and noticed on

http://hood.ie/intro/#get-started

to the left of the **TAKE A LOOK BEHIND THE MAGIC** section the link for "Work' is linking to some streaming thing and trying to force you to download stuff and bring you down a rabbit hole to some really weird stuff.

**Comment by gr2m** [comment]
cheers :+1:

**Comment by crswll** [comment]
No problem!
