### ISSUE TITLE
Add current contributors to community page

### ISSUE THREAD

**Issue by jennwrites** [hoodiehq/hood.ie#239]
Fixes https://github.com/hoodiehq/editorial/issues/68
Part of https://github.com/hoodiehq/hood.ie/issues/234
### :octocat: Starter Issue

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :relaxed:

---
### :computer: The Task

In preparation for the Camp Release we are trying to update the hood.ie site. This specific task involves updating the Hoodie community page to reflect our current contributors list. :dog: 
- [x] Claim this issue (@jo-porter)
- [x] Go to the `https://github.com/hoodiehq/hood.ie/blob/gh-pages/community/index.html`
- [x] Where the code is displayed (below a grey field) click on the pencil icon to the very right of the screen. 
  <img width="229" alt="screen shot 2016-02-23 at 17 50 39" src="https://cloud.githubusercontent.com/assets/2582805/13269553/641360f6-da56-11e5-8a5e-79dacd9ef39c.png">
- [x] Make your changes in the text field.
  - [ ] Move the following folks to the `COMMUNITY` section: Charlotte Spencer, Christoph Witzko, Nick Herr, Jenn Turner, Julia Simplicio, Patricia Garcia
- [x] Coordinate with the editorial teammate working on the copy issue here: https://github.com/hoodiehq/editorial/issues/68
- [x] Describe your edits briefly under where it says **Commit changes**.
  ![Commit changes](https://cldup.com/-uX5DjuDMN-1200x1200.png)
- [ ] Select the option to create a patch or a branch to begin the Pull Request process. 
- [ ] You are done :clap: comment below that your pull request is ready for review :tada:

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by jo-porter** [comment]
Howdy :) I'll take a run at this one, if I may?

**Comment by gr2m** [comment]
Howdy! Issue is all yours – welcome at Hoodie :wave: :dog:

**Comment by gr2m** [comment]
PR is ready her: https://github.com/hoodiehq/hood.ie/pull/252
