### ISSUE TITLE
localhost not working

### ISSUE THREAD

**Issue by chrisdemars** [hoodiehq/hood.ie#268]
I cloned the repo and ran npm install and grunt, I opened a browser at localhost:4000 and :1337 and I have been getting errors. What am I doing wrong?

**Comment by NickColley** [comment]
hey @chrisdemars 

What errors are you seeing? :)

**Comment by chrisdemars** [comment]
The first error was a "cannot /get" I believe, and the second was a page
error. Sorry I can't send any screen shots, I am at work right now. I think
I might need some guidance as how to contribute to this project. I was
going to work on some accessibility stuff, but being a future-proof dev, I
don't want to break anything lol.

**Comment by sebbel** [comment]
hey @chrisdemars, did you manage to get it running with upgrading jekyll?

**Comment by chrisdemars** [comment]
I upgraded but I haven't even tried yet.

**Comment by verpixelt** [comment]
Hey @chrisdemars please try again and see if it works. Was able reproduce it on my machine and upgrading resolved it. I will close the issue for now. Please comment, or contact us on Slack if you need help to get it running on your machine.
