### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by saiberz** [hoodiehq/hood.ie#289]
This link https://github.com/snnd/todomvc-on-hoodie from
https://github.com/hoodiehq/hood.ie/blob/823d68e8af7ec57fb2fff312a61ad7ad4ec32b0c/intro/index.html#L243
is not working.

**Comment by saiberz** [comment]
I've found this repo that has the same name and author as contributor but in another github account:
https://github.com/jspenc72/todomvc-on-hoodie
Could i submit a PR changing this link?

**Comment by gr2m** [comment]
Absolutely, thanks! PRs are always welcome :)
