### ISSUE TITLE
Style API

### ISSUE THREAD

**Issue by verpixelt** [hoodiehq/hood.ie#29]

**Comment by zoepage** [comment]
What does this mean?

**Comment by verpixelt** [comment]
I have no freakin clue. Was something I've copied from the TitanPad.

**Comment by zoepage** [comment]
cc @espy ?

**Comment by zoepage** [comment]
ping @espy

**Comment by espy** [comment]
No idea either :/ Sorry. Probably docs, though. I'd close it.

**Comment by zoepage** [comment]
this issue is for the API docs
