### ISSUE TITLE
[Blog Post]: Beyond Progressive Web Apps Part 3

### ISSUE THREAD

**Issue by janl** [hoodiehq/hood.ie#303]
Hey all, here is part 3 of the beyond PWA’s series. It is as of yet unedited (unlike the other two), and I’d love your help shaping this it can be published tomorrow or Thursday, EU morning time.

Here is a Google doc that you should all be able to comment on: https://docs.google.com/document/d/1qyrH0r4jPV9JJ-2maPpdY7ErCcY4JpKRsAGY5NkDW0w/edit#heading=h.wn5yk8z6mvar

Thanks all for your help <3

**Comment by jennwrites** [comment]
I left suggestions and comments. 

This has been a fun series because now I understand how it works (!!!) even if I'll never use it, lol

**Comment by janl** [comment]
@renrutnnej thanks so much! And you never know! ;)

Closing in favour of PR: https://github.com/hoodiehq/hood.ie/pull/304
