### ISSUE TITLE
Headline not showing up on events page

### ISSUE THREAD

**Issue by jennwrites** [hoodiehq/hood.ie#326]
### 🐛 The bug:

I noticed a bug while looking at the upcoming events for Hoodies (on http://hood.ie/events/). It seems like the closest event to the present loses its header in the active field. 

![events bug](https://cldup.com/_1AMkFo6ra.png)

I imagine this requires taking a look at https://github.com/hoodiehq/hoodie-css but I'm not sure what else is needed to fix it.

**Comment by gr2m** [comment]
problem is the header & background color are the same :) I’m looking into it
