### ISSUE TITLE
Slack Invite Server Error

### ISSUE THREAD

**Issue by hollenberry** [hoodiehq/hood.ie#329]
Hey Hoodies!

I was super excited to discover you on #Hacktoberfest, and started digging in to learn more about you 😄 

Unfortunately, it looks like there might be an issue with Slack invitations, as seen here:

<img width="1861" alt="screen shot 2016-09-27 at 5 12 29 pm" src="https://cloud.githubusercontent.com/assets/13326548/18896353/f412a1ec-84d5-11e6-8f5c-5ab127186d14.png">

I'm running Chrome, and ran into the same error while testing Safari. 

Thought that I'd make you aware! 

Props for having the nicest README.md that I've seen so far 👍 🎉 😄 
<img width="1232" alt="screen shot 2016-09-27 at 3 29 54 pm" src="https://cloud.githubusercontent.com/assets/13326548/18896369/1d5128bc-84d6-11e6-9e46-e595555c4a27.png">

**Comment by machikoyasuda** [comment]
This is one of the best issues I have seen written lately :) I love the screenshots of the error. Thank you @hollenberry for making this issue so easy to understand and replicate. I got the same 503 error too: https://www.dropbox.com/s/ue9ec390m52wn2h/Screenshot%202016-09-27%2017.29.03.png?dl=0 `XMLHttpRequest cannot load https://hoodie-slack.herokuapp.com/invite. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://hood.ie' is therefore not allowed access. The response had HTTP status code 503.`

**Comment by gr2m** [comment]
Thanks @hollenberry, we could reproduce the issue, problem is that the slack invite form needs an app which is running on Heroku, and we run out of quota :( @janl will move it to another server tomorrow to fix it for good.

Until then, can you tell me your email address, and I will add you to slack? You can also dm me on twitter, my direct messages are open: https://twitter.com/gr2m

**Comment by hollenberry** [comment]
Hey there! Closing this out because it looks like you've got Slack working!
