### ISSUE TITLE
Add illustrations and /zoo

### ISSUE THREAD

**Issue by verpixelt** [hoodiehq/hood.ie#34]

**Comment by lenareinhard** [comment]
I have a suggestion … idea: launch /zoo, but only with the first animal (dog). add "coming soon bla" below (not necessarily literally). And then we can add the other animals over the time.
(thing is: the dog will be in the launch anyway, as it's on the index page, and so it doesn't stand there without any context)
(this would make parts of this issue pre-launch)

**Comment by lenareinhard** [comment]
see #40, I'm on it
