### ISSUE TITLE
Add license to this repository

### ISSUE THREAD

**Issue by RichardLitt** [hoodiehq/hood.ie#346]
This currently isn't licensed! Oh no! Can I use it?

**Comment by gr2m** [comment]
lol Richard, this website code is such a mess :D The website footer says

> © 2012-2016 the Hoodie Community and other contributors. Hoodie is licensed under the Apache License 2.0.
> All pictures, photos and illustrations are owned by the Hoodie Open Source Project and licensed under CC BY-NC-ND 4.0.

Does that help already? For the website source code we should add an Apache 2.0 license, feel free to send a pull request copying a LICENSE file from one of the other repos

**Comment by RichardLitt** [comment]
That doesn't actually say what the site is licensed under; that mentions the hood.ie project, which I assume is the code in the main repo, and the assets, but not the code. 

Will copy a file. One second.
