### ISSUE TITLE
Bug: Grammatical Error and Possible Typo in Get-Started section

### ISSUE THREAD

**Issue by theNaut1lus** [hoodiehq/hood.ie#357]
URL : http://hood.ie/intro/#get-started

<img width="644" alt="Screenshot 2019-03-24 at 1 08 26 PM" src="https://user-images.githubusercontent.com/35738138/54876490-b72eaa00-4e36-11e9-8f76-5a2f842933dc.png">

the line `you who build something...` should be read as `you who builds something on it, don't have to worry about backends`

so basically change `build` -> `builds` and add a comma before `don't` to separate the conjuncture in the two sentences there 

Seems like an easy fix and I would like to implement this as my first issue here. 🥇

**Comment by gr2m** [comment]
Sounds good to me 👍 It's been a long time since I worked on the website, but I think the change should be as simple as directly edit content files :)

**Comment by theNaut1lus** [comment]
Please review @gr2m
