### ISSUE TITLE
Optimisation of the critical rendering path

### ISSUE THREAD

**Issue by verpixelt** [hoodiehq/hood.ie#37]

**Comment by zoepage** [comment]
Can we close this now @verpixelt ?

**Comment by verpixelt** [comment]
Nope we haven't done anything to fix that.

**Comment by zoepage** [comment]
Could you provide more information here, so maybe someone else can take this task?

**Comment by verpixelt** [comment]
To resolve this issue one has to refactor parts of the CSS. I ran the Google PageSpeed Insights and a bunch of other tests. Our CSS is blocking page rendering. 
<img width="1660" alt="critical" src="https://cloud.githubusercontent.com/assets/1640079/9169351/3d4438f6-3f5b-11e5-9685-29152166df0a.png">

Tasks would be:
- [ ] detect above the fold CSS
- [ ] Inline critical CSS
- [ ] load missing bits of the CSS later

**Comment by zoepage** [comment]
cool, thank you for that! <3

**Comment by NickColley** [comment]
I've used https://github.com/filamentgroup/criticalCSS with some good success.
- Generate criticalCSS
- Check for cookie for first time visitors
- https://github.com/filamentgroup/loadCSS
- Set cookie and load full CSS file (from the cache) next time.

Next visits you can detect your cookie and just supply the full CSS.

With hoodie there's quite a few pages so what will render above the fold on one page wont work on others.

What you can do is if your templates are sane, generate the inline css for each template, obviously this is more complicated but doable.

This is all pretty reasonable to execute but really needs to be automated or you can risk having new CSS updates not included and then the page will render incorrectly.

**Comment by zoepage** [comment]
Depending on all the pages we have to maintain and the very little amount of time we have to finish this talk right now, I'd say we postpone this task again after the 1.0 launch.

**Comment by verpixelt** [comment]
By now the CSS has moved to a separate repo and how we proceed from here is sill not defined. I will close that issue now bc, there will be a lot of changes on how we gonna use the CSS no matter what.
