### ISSUE TITLE
remove wrong username from disqus

### ISSUE THREAD

**Issue by svnlto** [hoodiehq/hood.ie#4]
https://github.com/zoepage/hoodie-website-css/blob/gh-pages/_includes/disqus.html#L4

;)

**Comment by verpixelt** [comment]
Yep, thanks for pointing out ;)

**Comment by verpixelt** [comment]
I've created a new site on Disqus called "hood.ie"(respectively hoodie-blog). At the moment I'm the primary moderator but I'm able to invite additional moderators and change the primary acc as well(I just need the Disqus username). I've also swapped the variable in the Disqus snippet.
![disqus](https://cloud.githubusercontent.com/assets/1640079/4910155/9f8535da-647b-11e4-9aa4-0ce2fa8d4abf.png)

**Comment by lenareinhard** [comment]
thank you!
my Disqus handle is https://disqus.com/Frau_Fuchs

**Comment by verpixelt** [comment]
git push --force whoop whoop :palm_tree:
I can't simply change the primary acc. Therefor I have to contact the Disqus support. In order to do that I need your e-mail Adress – "email address of new primary moderator". ([removed] I guess!?)

**Comment by lenareinhard** [comment]
@verpixelt nope, [removed](ping me when you got that, then I'll remove the addresses from the comments before the repo goes public)
thank you!

**Comment by verpixelt** [comment]
Support ticket sent. _ping_ @ffffux

**Comment by lenareinhard** [comment]
@verpixelt received, checked, it's all in. Thank you! :sunny:
