### ISSUE TITLE
Add Workshop + workshop materials to /contribute

### ISSUE THREAD

**Issue by lenareinhard** [hoodiehq/hood.ie#44]
- Google Doc
- Tutorials
- …

**Comment by lenareinhard** [comment]
This can be done by anyone. Main task is to finish the workshop materials (they're here: https://docs.google.com/a/thehoodiefirm.com/document/d/1HijseqxQvPO9auzBuobPvuzv5Y3XQaf_g0u1fhJ3jvo/edit#  – I've written most parts, but some tutorials and stuff are missing (added comments for these in the doc)

**Comment by zoepage** [comment]
That's why I assigned you. When you are done, you can assign me and I'll finish this task.

So, we always know who is responsible atm.

**Comment by lenareinhard** [comment]
Done with my parts, I don't know who can work on it now (but it's also not urgent anyway).

**Comment by lenareinhard** [comment]
I have now made a new issue for the workshop content in the docs repo (as it rather belongs there than here) https://github.com/hoodiehq/documentation/issues/78
Assigned myself for this issue here – once the workshop content (= that doc and all things related) is ready, I will put it on the website.

**Comment by lenareinhard** [comment]
first iteration is done in hood.ie/contribute#meetups, can be extended there as soon as the docs are ready
