### ISSUE TITLE
Set up coding guidelines

### ISSUE THREAD

**Issue by verpixelt** [hoodiehq/hood.ie#45]
- [x] HTML
- [x] Sass
- [ ] Javascript

**Comment by verpixelt** [comment]
I've added the first rules to the coding standards(HTML & Sass). This is an ongoing task. @zoepage can you please provide content for the Javascript part!?

**Comment by gr2m** [comment]
Let's leave it open for now please, I don't want this to be forgotten

**Comment by zoepage** [comment]
Those are just coding guidelines for the website && the framework. We've done this.

**Comment by gr2m** [comment]
When you close it, could you please point to the places where it's done? That'd help a lot :)

Are the JavaScript guidelines done, too?

**Comment by zoepage** [comment]
We are adding them to the http://hoodiehq.github.io/hoodie-css/
