### ISSUE TITLE
feature: build version 2 of the website using harp.js

### ISSUE THREAD

**Issue by svnlto** [hoodiehq/hood.ie#5]
post launch I'd like to migrate the website to http://harpjs.com/. It's a jekyll equivalent without the ruby dependencies, has preprocessors built-in and fit's way better into the stack.

**Comment by HipsterBrown** [comment]
+1

Started using this recently, it's a great tool and makes it much easier to get up and running. I have not tried using it with grunt or any other sort of build tool for deployment but I have used it to make a ph-pages friendly static site. [my harp.js site example](https://github.com/HipsterBrown/DF-Resonsive)

**Comment by janl** [comment]
we gotta sort sort auto-deploy and some real hosting then, too, because I’d like to retain the “merge PR to deploy” semantics, but that is not too hard to set up. Just flagging this as a requirement :)

**Comment by HipsterBrown** [comment]
There is the [Harp Platform](https://www.harp.io/) with some [collaboration support](https://www.harp.io/docs/platform/collaborators). Files are hosted through Dropbox, which might be a turn-off for this team, and have GUI controls for publishing and build backups. 

[Or keep using gh-pages deploy method.](http://harpjs.com/docs/deployment/github-pages)

**Comment by janl** [comment]
I’d set up a custom system somewhere. gh-deploy does’t give you GH-merg capabilities, or am I reading that wrong?

**Comment by HipsterBrown** [comment]
That is true. You need to compile the site before pushing to Pages. I guess you could set up a githook to deploy to harp server running on [heroku](http://harpjs.com/docs/deployment/heroku) or another linux box after approved merge. 

While harp makes local development easier to get started and iterate, but it's hard to beat the easy deployment workflow of Jekyll on gh-pages. ¯_(ツ)_/¯
