### ISSUE TITLE
fix broken blog posts

### ISSUE THREAD

**Issue by lenareinhard** [hoodiehq/hood.ie#50]
- [x] http://blog.hood.ie/2014/01/how-is-hoodie-funded/
- [x] http://blog.hood.ie/2014/05/welcome-to-the-neighbourhoodie/
- [x] http://blog.hood.ie/2013/11/say-hello-to-offline-first
- [x] http://blog.hood.ie/2014/02/non-coders-in-open-source-projects-or-on-aliens-confessions-of-a-non-coder-1
- [x] http://blog.hood.ie/2014/02/confessions-of-an-alien-or-the-ultimate-guide-to-attracting-non-coding-contributors-to-your-open-source-project-2/
- [x] http://blog.hood.ie/2014/05/a-hoodie-for-you-7-prototypo

**Comment by verpixelt** [comment]
- [ ] Replace image resources

**Comment by verpixelt** [comment]
Will fix that tonight.

**Comment by verpixelt** [comment]
Optimised as far as possible at this stage.
