### ISSUE TITLE
/sponsoring: felder unten auf der seite stylen

### ISSUE THREAD

**Issue by lenareinhard** [hoodiehq/hood.ie#53]

**Comment by zoepage** [comment]
cc @espy

**Comment by zoepage** [comment]
Is this issue done with the following or is there more to do? If so, please specify the task!
![bildschirmfoto 2014-11-14 um 16 42 21](https://cloud.githubusercontent.com/assets/562354/5048339/3894afbe-6c1d-11e4-9258-cb4fae317282.png)

**Comment by lenareinhard** [comment]
Imo completely fine like that, thanks!
