### ISSUE TITLE
img class="no-border" still displays borders

### ISSUE THREAD

**Issue by lenareinhard** [hoodiehq/hood.ie#54]
Firefox (latest version)
![screen shot 2014-11-04 at 12 35 06](https://cloud.githubusercontent.com/assets/3472712/4898982/b039f312-6416-11e4-8a3c-c215c39308a0.png)

Chrome (yes, with the link display :) ) (latest version)
![screen shot 2014-11-04 at 12 35 49](https://cloud.githubusercontent.com/assets/3472712/4898986/bfa16574-6416-11e4-9848-b259e91f852f.png)

**Comment by verpixelt** [comment]
I will take a look at it, tonight. (btw. your type doesn't look that fat anymore :P)

**Comment by verpixelt** [comment]
Fixed.
![fix-54](https://cloud.githubusercontent.com/assets/1640079/4904981/e29de96e-644b-11e4-99bf-49c91e58de20.png)
