### ISSUE TITLE
Tasks for Docs Launch

### ISSUE THREAD

**Issue by lenareinhard** [hoodiehq/hood.ie#56]
- [x] comment in docs.hood.ie in all _includes/header… files again (commented out atm)
- [x] same for footer.html
- [x] index.html (front page): github.com/hoodiehq/documentation ersetzen
- [x] _config.yml: add '- title: Documentation
  url: 'http://docs.hood.ie' ' to sub-navigation-get-help

**Comment by verpixelt** [comment]
What prevents us from including docs into the initial launch?

**Comment by lenareinhard** [comment]
@zoepage 
[edit: that wasn't necessarily the direct answer to your question ;) ]

**Comment by lenareinhard** [comment]
ok, das ist noch offen:
Hier die Randinfos (copy-paste aus einer Mail von Ola an Stephan):
CSS Framework: 
https://github.com/zoepage/hoodie-css/
// In der Readme steht drin, wie es zu benutzen ist.

View:
https://github.com/zoepage/hoodie-website-css/blob/gh-pages/doku.html
Hier ist der Content noch nicht gestyled. Aber das kannst du einfach so nehmen, wie es im Repo ist, nehmen. Wenn du da noch Hilfe brauchst oder Infos, meld dich :)

Docs:
https://github.com/hoodiehq/documentation
// Die Review der Struktur mach ich sehr zeitnah. Denke, diese Woche noch.
Ansonsten würde ich dich bitten, alle files mal zu reviewen. Schauen, was noch fehlt und wenn du kannst, das zu ergänzen. Die account.md muss aufgeräumt werden. Da gab es einen bösen Mergekonflikt. 

API:
https://github.com/hoodiehq/hoodie.js/tree/docs
// Hier hat Sven bereits ein Template geschrieben mit Jade. Das ist super so ;) Wenn du willst, kannst du das auch wieder verwenden für die Docs. GH-Pages ist aber bei den Docs bereits aufgesetzt.
