### ISSUE TITLE
Fix includes

### ISSUE THREAD

**Issue by verpixelt** [hoodiehq/hood.ie#57]
Something went wrong with your last commits ecbf6cdc769f4600933a93f34d25fa63e57450b6. I've applied a hotfix 9f8e1e2d408723e6631c47f631294829fbb470ef de406eadef7c8d40262164c63d7b82423dede7c4 but these files are just empty to prevent Jekyll from aborting its build tasks.

**Comment by zoepage** [comment]
cc @espy

**Comment by espy** [comment]
Wow, super stupid mistake on my part. I'm on it.
