### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by zoepage** [hoodiehq/hood.ie#58]
![bildschirmfoto 2014-11-04 um 21 52 57](https://cloud.githubusercontent.com/assets/562354/4907822/9e0243fe-6464-11e4-8e75-91d212a638ca.png)
can't compile

cc @verpixelt

**Comment by verpixelt** [comment]
Please update I've fixed that with c1875cf12b29701321ed2fa0d19ae5d715b6c024 3h ago.

**Comment by zoepage** [comment]
I pulled 20 min ago

**Comment by verpixelt** [comment]
I removed all silent classes right now. Pull and try it again. Should work now.

**Comment by zoepage** [comment]
now it works... so is this an issue...
![bildschirmfoto 2014-11-04 um 22 04 00](https://cloud.githubusercontent.com/assets/562354/4907987/27efec6e-6466-11e4-848b-419455e62f2d.png)

**Comment by verpixelt** [comment]
This is caused by the missing nav elements -_- Doesn't look nice but I have no good idea right now how to avoid that.

**Comment by zoepage** [comment]
so, it doesn't look like a good idea to work on the nav atm? :/

**Comment by verpixelt** [comment]
0_o the amount of links shouldn't hinder you to implement the missing functionality.

**Comment by zoepage** [comment]
i didn't ment the navigation. i ment the 7px padding on the top and left. there are also many bugs atm. that's why I asked.

**Comment by verpixelt** [comment]
![browser](https://cloud.githubusercontent.com/assets/1640079/4908345/1a495138-6469-11e4-905b-b8dfac7b64f9.png)
Can't see any of them.

**Comment by verpixelt** [comment]
There was an issue with the width of the logo. I'm sorry for that. Fixed a FF bug in the blog section and created the one in the main nav. Pushed a fix for both now.
