### ISSUE TITLE
create own sub-navigation for /initiatives

### ISSUE THREAD

**Issue by lenareinhard** [hoodiehq/hood.ie#60]
items to be displayed:
- /initiatives#offline-first Offline First
- /initiatives#nobackend noBackend
- /initiatives#noncoders Non-coding People
- /initiatives#dreamcode Dreamcode
- /initiatives#tools Tools

**Comment by verpixelt** [comment]
Done.
![initiatives](https://cloud.githubusercontent.com/assets/1640079/4909997/7d7dd688-6479-11e4-9752-9e04edf3b422.png)

**Comment by lenareinhard** [comment]
muoah! <3

**Comment by lenareinhard** [comment]
sub-navigation is not displayed currently, couldn't find the reason
![screen shot 2014-11-05 at 09 25 32](https://cloud.githubusercontent.com/assets/3472712/4914659/c11f89f8-64c5-11e4-813e-3b4740ef507e.png)

**Comment by verpixelt** [comment]
Please take a look at the comment on #66.

**Comment by lenareinhard** [comment]
solved it, thanks
