### ISSUE TITLE
finish Club

### ISSUE THREAD

**Issue by lenareinhard** [hoodiehq/hood.ie#61]
(task mainly for Alex, Jan, Lena, to be coordinated; see also #41 for club launch

**Comment by lenareinhard** [comment]
assigned me, I'll keep track of it for now and will hand it over as soon as necessary

**Comment by zoepage** [comment]
@espy && @gr2m && @janl 

What about the Club? Are we able to finish for 1.0 launch or can we close and open, when we'll work on this again?

**Comment by gr2m** [comment]
I'd say let's close and reopen it later, it's not in scope for 1.0
