### ISSUE TITLE
Write + add further animal stories + animal pics

### ISSUE THREAD

**Issue by lenareinhard** [hoodiehq/hood.ie#62]

**Comment by zoepage** [comment]
Is there someone who can take care of this?

**Comment by varjmes** [comment]
@zoepage What kind of animals and stories would we like? :)

**Comment by gr2m** [comment]
we are making separate issues on the editorial repo now:
- https://github.com/hoodiehq/editorial/issues/64
- https://github.com/hoodiehq/editorial/issues/65
- https://github.com/hoodiehq/editorial/issues/66

stay tuned :)
