### ISSUE TITLE
blog is not displayed anymore

### ISSUE THREAD

**Issue by lenareinhard** [hoodiehq/hood.ie#66]
FF & Chrome. Might be related with #57 
![screen shot 2014-11-05 at 09 24 19](https://cloud.githubusercontent.com/assets/3472712/4914603/296d5298-64c5-11e4-8652-1cac0e103253.png)

**Comment by verpixelt** [comment]
For both the changes on the blog and also the changes on #60 I had to adjust stuff in the config.yml. Jekyll doesn't recognize these changes until a restart. Can you try that please.

**Comment by lenareinhard** [comment]
Ok, awesome, fixed it. Sorry and thank you!

**Comment by verpixelt** [comment]
Don't be. It's something you couldn't know.
