### ISSUE TITLE
[pre-launch] css - tasks

### ISSUE THREAD

**Issue by zoepage** [hoodiehq/hood.ie#67]
Soft launch will be at 6pm. Release tomorrow at 11am.

@verpixelt :
- [x] finish Grunttasks
- [x] move all files to hoodie-css
- [x] kick out not used css files in website and blog

@zoepage:
- [x] move hoodie-css to hoodiehq
- [x] point css links to hoodie-css for FAQ, Blog & Website
- [x] point css links to hoodie-css for Club
- [x] kick out not used css files in club & FAQ

@verpixelt & @zoepage:
- [x] talk about switch to hoodie-css
  -> which files need to stay in other repos, which need an update of the path?

**Comment by lenareinhard** [comment]
@zoepage please add #10 (items from this issue missing)

**Comment by lenareinhard** [comment]
note: renamed issue to "pre-launch" and removed "post launch" label; all of this has to be done before the launch.

**Comment by espy** [comment]
@zoepage @verpixelt I tried linking club to use 'https://raw.githubusercontent.com/hoodiehq/hoodie-css/master/src/css/hoodie.css' but that doesn't work, it's loaded but not applied to anything. Not sure why, could it be something to do with `https` vs `http`? Because loading CSS via `http` from a gh-page worked.

**Comment by verpixelt** [comment]
Sry, I've no clue. Do you have a link where I can have a look?

**Comment by zoepage** [comment]
I'll check as soon as I'm at the office.

**Comment by zoepage** [comment]
maybe bc the repo wasn't in hoodiehq before? might want to try it now @espy ?

**Comment by verpixelt** [comment]
@zoepage what's about this tasks? Haven't we done most of them already? I can definitely mark the "kick out not used css files in website and blog" task as done.
