### ISSUE TITLE
Blog posts all italic in overview pages

### ISSUE THREAD

**Issue by lenareinhard** [hoodiehq/hood.ie#71]
all posts before are displayed correctly in the overviews, but starting with the 2nd, 4th, 5th post, they're all italic.
Blog post view is correct, only overview is wrong, e.g. as in 
![screen shot 2014-11-05 at 20 35 49](https://cloud.githubusercontent.com/assets/3472712/4925112/84c8dd8e-6528-11e4-9dda-6f8a2c480f6d.png)

**Comment by verpixelt** [comment]
That are remains from the Wordpress blogpost formatting which we have to clean up. It's a no brainer but not a small task.

**Comment by lenareinhard** [comment]
good to know. will stick with labelling this "post-launch".

**Comment by verpixelt** [comment]
I've fixed a few more blog posts. All from page 1 to page 3 are fine by now. We could close this ticket or leave it open if you think we should clean more posts from the past.

**Comment by zoepage** [comment]
I think, the last 3 pages are ttly fine as long as nobody writes an issue for that. So let's close it and reopen, if needed :)
