### ISSUE TITLE
Pages broken in Safari

### ISSUE THREAD

**Issue by lenareinhard** [hoodiehq/hood.ie#74]
Safari, latest version

broken atm:
- grid is not displayed correctly
- main navigation is not displayed correctly
- main navigation has underlines displayed 
- underlines are displayed wrong

![screen shot 2014-11-06 at 11 37 15](https://cloud.githubusercontent.com/assets/3472712/4934353/e7bf01e8-65a0-11e4-9a3c-eb4df8ec4240.png)
![screen_shot_2014-11-06_at_11 35 09_](https://cloud.githubusercontent.com/assets/3472712/4934369/153ab842-65a1-11e4-867e-a129dc4fa373.png)

same / similar for Safari Mobile 

![img-20141106-wa0000](https://cloud.githubusercontent.com/assets/3472712/4935238/00e9fa0c-65aa-11e4-9edc-384c29f6db18.jpg)
![img-20141106-wa0000](https://cloud.githubusercontent.com/assets/3472712/4935239/04be202c-65aa-11e4-881b-557ae98e7b91.jpg)
![img-20141106-wa0001](https://cloud.githubusercontent.com/assets/3472712/4935240/04e55458-65aa-11e4-9ae0-b6fec5b9629a.jpg)
![img-20141106-wa0002](https://cloud.githubusercontent.com/assets/3472712/4935241/07f3f118-65aa-11e4-946e-b98d44ef0831.jpg)
![img-20141106-wa0002](https://cloud.githubusercontent.com/assets/3472712/4935242/0b0f8e98-65aa-11e4-854a-04f186b29bcb.jpg)
![img-20141106-wa0003](https://cloud.githubusercontent.com/assets/3472712/4935243/0b12c752-65aa-11e4-9338-62a382903b25.jpg)

**Comment by verpixelt** [comment]
Will be solved with the prefixed CSS file.

**Comment by verpixelt** [comment]
Fixed. If its broken from time to time it's because we haven't included the prefixed CSS. Won't happen if the page is live.
