### ISSUE TITLE
link underlining broken in Chrome

### ISSUE THREAD

**Issue by zoepage** [hoodiehq/hood.ie#78]
![bildschirmfoto 2014-11-06 um 14 02 45](https://cloud.githubusercontent.com/assets/562354/4936113/4d7fa6cc-65b5-11e4-8a67-db1da8d96139.png)

Maybe the FF fix killed that? :)

It's JUST (!) in the .teaser section...

**Comment by verpixelt** [comment]
Jep, will fix that later.

**Comment by zoepage** [comment]
Thank you <3

**Comment by verpixelt** [comment]
- [x] /events
- [x] teaser paragraph
