### ISSUE TITLE
Link highlighting lilac and gray

### ISSUE THREAD

**Issue by verpixelt** [hoodiehq/hood.ie#8]
The link highlighting for lilac and gray is not recognisable. (link highlighting for all color schemes to stay consistent) Please put a bit more effort into it instead of simply use text-decoration: underline:

**Comment by zoepage** [comment]
- aside and blue

**Comment by zoepage** [comment]
we need to stick with underline atm (bc of time issues), but can definitely do something much cooler later!

**Comment by verpixelt** [comment]
I've tried something last night (last commit not yet copied into the hoodie-css repo) which works pretty well except for Firefox. I will take a look into it after work.

**Comment by verpixelt** [comment]
I found a fix for the FF problem. Please @zoepage @ffffux @espy if you spot links where the underline appears more as a "strike-through" shout out and I'll fix it.
