### ISSUE TITLE
font weight in main-nav

### ISSUE THREAD

**Issue by zoepage** [hoodiehq/hood.ie#85]
Thinking about using the 400 font-weight of the font instead the 500 for the main-nav and the meta-nav. 
I need to check, if it looks fine with the `<strong>` text too...

**Comment by janl** [comment]
re-open because tmp fix.

**Comment by lenareinhard** [comment]
related with #89

**Comment by zoepage** [comment]
After changing the font-weight from 300 to 400, the active link isn't really visible anymore. Any suggestions? (Guessing the underlining got kicked out for a reason?)

cc @verpixelt

**Comment by lenareinhard** [comment]
@zoepage underlining got kicked out because 
a) had the same issue as all other links (looked rather crossed out than underlined)
b) UI should be consistent – and when links normally are underlined in their default state, it doesn't make sense to use the underline to communicate "active"

**Comment by zoepage** [comment]
that were my thoughts. do you think 300 is still an option for the main nav or do we need an alternative solution for the 400 weight?

**Comment by lenareinhard** [comment]
Suggestion: 
- leave 300 for now, as it's fine in Chrome which is the browser that most people use (are using now and have been using our website with over the past >1 year
- should we hear more feedback about readability / usability, re-open issue.

Alternative: think about different solution now. Still, for now, this is an enhancement topic, and maybe over the time we gain more feedback and can think about a better solution. Or someone who wants to contribute can take this topic and think about an approach.

**Comment by zoepage** [comment]
Sounds like a plan!
I'll close the issue then and wait for more feedback.
