### ISSUE TITLE
bug when navigating to a page from the footer on mobile / smaller devices (navigating from footer broken)

### ISSUE THREAD

**Issue by lenareinhard** [hoodiehq/hood.ie#88]
what I did:
- opened prev.hood.ie/contribute (or any other page, also goes for index.html) with reduced page width (only reduced menu with hamburger icon was shown); or opened same page on mobile device
- scrolled to footer
- clicked on "Get help" (or any other link)
- now all that happens is: 
  - page scrolls back to the top
  - and displays navigation, with the page I had opened before selected
  - now all I can do is close the navigation, and then I'm still on the same page

Problem throughout Safari, Chrome, Firefox (mobile + desktop). Works like a charm on full-width screens.

Which means: I can't navigate to another page from the footer on a mobile device.

**Comment by lenareinhard** [comment]
@espy can you take a look at this?

**Comment by espy** [comment]
Yip yip!

**Comment by verpixelt** [comment]
![](http://i62.photobucket.com/albums/h97/ValleyVenus/yip-yip-yip.gif)
