### ISSUE TITLE
font weight in boxes with background text

### ISSUE THREAD

**Issue by janl** [hoodiehq/hood.ie#89]
Things are a tad hard to read when boxes have a background colour or image:

![screen shot 2014-11-11 at 10 40 09](https://cloud.githubusercontent.com/assets/11321/4991019/3c54f89c-698f-11e4-850a-ba14797eb6b5.png)
![screen shot 2014-11-11 at 10 41 09](https://cloud.githubusercontent.com/assets/11321/4991020/4115f7f0-698f-11e4-94ea-e0079086459b.png)

(Safari, Yosemite, non-retina)

**Comment by lenareinhard** [comment]
is that a bug? (bugs are showstoppers for the launch)

**Comment by janl** [comment]
I’d say at least the orange box is a blocker, as it is the first thing people see.

**Comment by lenareinhard** [comment]
alright, then we postpone the launch until someone can work on this. This is about the fonts and weights which we use + embed, and has to be taken a look at regarding design + speed topics.

**Comment by janl** [comment]
someone from the design team: feel free to overrule me

**Comment by espy** [comment]
We already use font weight 500 in other places, so we can do this without importing any new font cuts.

**Comment by janl** [comment]
:+1:

**Comment by lenareinhard** [comment]
Yes, we can use font weight 500, and I completely get why this topic is an issue. Only thing is that 500 wasn't planned to be used here (at least not for paragraphs), and I'd like to have at least @zoepage take a look at this before this goes live like that.

**Comment by janl** [comment]
aye.

**Comment by lenareinhard** [comment]
see also #85

**Comment by verpixelt** [comment]
Font weight 300 and 500 as well do look too light and/or too bold in the different browsers based on the varying font rendering(and also on retina and non-retina). As @zoepage already mentioned in #85 the 400er could be a solution. I could/would implement the specific style only for the index page tonight as "hotfix" so we solve the "launch blocker" and can discuss this topic further afterwards.

**Comment by janl** [comment]
@verpixelt sounds like a plan.

I think I’d be happy to choose ugly over hard to read, but it is a bit of an eye-sore now, and I’m not calling the shots here.

**Comment by janl** [comment]
500 / italic doesn’t look too shabby here:

![screen shot 2014-11-11 at 12 13 09](https://cloud.githubusercontent.com/assets/11321/4992120/63836e14-699c-11e4-8776-a4609c088071.png)

(_non-designer annoys everyone, then runs and hides_)

**Comment by janl** [comment]
@verpixelt had a quick call with @zoepage, she suggested we throw out the loading of the monospace font in the process, since it is not used yet. I went ahead and did the change, I hope you don’t mind! :)
