### ISSUE TITLE
[/index.html] make ”Meet the Hoodie” box clickable

### ISSUE THREAD

**Issue by janl** [hoodiehq/hood.ie#90]
currently only the text “meet the hoodies” is a click target. I’d be nice to make the whole box clickable.

Not blocking the launch.

**Comment by zoepage** [comment]
After checking, I think the solution is great. Are there any problems with that I do not know about?
(Working on desktop and mobile like a charm) ;)

cc @verpixelt

**Comment by verpixelt** [comment]
I've merged the fix yesterday. I'll close this ticket.
