### ISSUE TITLE
Redirect /sponsoring.html somewhere

### ISSUE THREAD

**Issue by BigBlueHat** [hoodiehq/hood.ie#94]
The old sponsoring.html page currently 404's. It should likely be a redirect to wherever that content lives now.

Found via the (currently) pinned tweet at https://twitter.com/lrnrd

Cheers!

**Comment by lenareinhard** [comment]
@BigBlueHat ha, and that's my tweet even! Thanks for the hint, will work on it (see also #97)

**Comment by janl** [comment]
fixed
