### ISSUE TITLE
cheatcheats and bug page are 404s

### ISSUE THREAD

**Issue by JosePedroDias** [hoodiehq/hood.ie#96]
The cheatsheet links ("Web Version" and "Print Version" here http://hood.ie/get-help/) and bug submitting page ("report a bug" here http://hood.ie/contact/) are 404s.

**Comment by janl** [comment]
where do you the 404s? the links you posted work for me

**Comment by JosePedroDias** [comment]
This URL for example:
http://hood.ie/dist/presentations/hoodie-cheat-sheet.pdf
returns title 404 and heading We're sorry...
Maybe it's caching, don't know...

**Comment by janl** [comment]
Ah, I understand now, thanks, confirmed!

**Comment by lenareinhard** [comment]
@JosePedroDias thanks for the feedback! 
Quick check:
- "report a bug" on http://hood.ie/contact/ -> can't reproduce (link is hood.ie/bug)
- Cheat Sheet links:
  - Web -> fixed
  - Print -> fixed

**Comment by zoepage** [comment]
@JosePedroDias is the bug still occurring? Couldn't reproduce it either :)

**Comment by JosePedroDias** [comment]
all the bugs are fixed. Thanks!

**Comment by zoepage** [comment]
AWESOME! thanks!
