### ISSUE TITLE
discuss further website maintenance, responsibilities and set up maintenance team

### ISSUE THREAD

**Issue by lenareinhard** [hoodiehq/hood.ie#99]
@zoepage assigned you for now

**Comment by verpixelt** [comment]
I would like to help finish this project and provide further support as well as maintenance for the code base. Also there is a lot more to refactor, optimise and to document. It would be awesome to work with @zoepage together as we both know the whole structure and ideas behind how this page was build.

**Comment by zoepage** [comment]
+1

**Comment by zoepage** [comment]
So, no one else is answering, shall we close the issue with the decision that @verpixelt and I will take care of the last issues?

**Comment by NickColley** [comment]
I'd be willing to help out :)

**Comment by verpixelt** [comment]
@zoepage I guess for now it is the best idea to do so. Once we've finalised the documentation we could onboard more people to help out.

**Comment by lenareinhard** [comment]
@zoepage @verpixelt this is definitely alright for getting the last issues done. It would be great though if this limitation is only temporary (as suggested, e.g. until the documentation is ready; we should also discuss how to handle content contributions, e.g. for the TGIF), and if you could also think about ways people can contribute to it in the future (which we could maybe even then put on the /contribute section).

**Comment by verpixelt** [comment]
I totally agree with you on that. However we'll need someone who holds the strings together even if the documentation is finished. And at this point I don't see this task on someone else than @zoepage and/or me.

**Comment by zoepage** [comment]
So, let's finish the last tasks, move the css to the framework repo and then open it up. Is this okay?

**Comment by verpixelt** [comment]
+1
